version: '2'
services:
  fluentd:
    image: csergey88/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks: 
      - monitoring_net

  elasticsearch:
    image: elasticsearch:7.4.0
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks: 
      - monitoring_net
    command: 
      - sh
      - -c
      - sysctl -w vm.max_map_count=262144

  kibana:
    image: kibana:7.4.0
    depends_on: 
      - elasticsearch
    ports:
      - "5601:5601"
    networks: 
      - monitoring_net


networks: 
  monitoring_net: