version: '2.0'
services:
  post_db:
    image: csergey88/mongodb:latest
    volumes:
      - post_db:/data/db
    networks:
      - reddit
    ports:
      - 27017:27017
  ui:
    image: csergey88/ui:latest
    ports:
      - 9292:9292/tcp
    networks:
      - reddit
    logging: 
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    image: csergey88/post:latest
    networks:
      - reddit
    depends_on: 
      - post_db
    ports:
      - 5000:5000
    logging: 
      driver: "fluentd"
      options: 
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    image: csergey88/comment:latest
    networks:
      - reddit


volumes:
  post_db:

networks:
  reddit: